.github/workflows/auto-readme.yml, .github/workflows/auto-release.yml, .github/workflows/release-branch.yml, profile/README.md, profile/banner/README.md
* Try to use `./banner/image.png` in hopes it will resolve relative to the `profile/` path.
* Add missing permissions, `runs-on`, and `GITHUB_TOKEN` 
* Wrong image displayed
* Releases are broken
=> Fix image path of profile on profile page

.github/workflows/auto-readme.yml, .github/workflows/release-branch.yml
* Check for README.yaml
* Add Job Summary
* Add permissions
* Debugging releases
=> More Release Fixes

.github/mergify.yml, .github/settings.yml, Makefile
* Use this repo as the organization's config for mergable
* Auto-merge readme/image updates
* Automate repo maintenance
=> Add mergable config

.github/mergify.yml, .github/settings.yml
* Use yaml anchors
* Treat github-actions as a bot
* This hopefully fixes merging
=> Fix mergify settings

README.md.gotmpl
* Fix references to GitHub Actions
* Copied from our default template that applied more to terraform modules
=> Update the readme template

.github/mergify.yml, .github/settings.yml, .github/workflows/release-branch.yml, .github/workflows/release-published.yml, .github/workflows/scheduled.yml, action.yml, scaffolding/.github/Makefile, scaffolding/github-action/.github/mergify.yml, scaffolding/github-action/.github/settings.yml, scaffolding/github-action/.github/workflows/scheduled.yml, scaffolding/github-action/Makefile
* Implement a github action used by the organization to manage scaffolding
* Run `make all` for a given repository type
* Add a workflow to test the scheduled runs
* Manage repos at scale
=> Create repo scaffolding

.github/workflows/release-branch.yml, .github/workflows/scheduled.yml
* checkout repo
* readme action expects repo to be checked out
=> Checkout Repo

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/release-branch.yml, CODE_OF_CONDUCT.md, LICENSE
- Force push new readme
- Add missing issue templates
- Fix broken URL
- Force pushing is required for pushing to protected branches with bypass permission
=> Force push readme

.github/workflows/release-branch.yml
- Remove flags that caused error
```shell
fatal: could not read Username for 'https://github.com': No such device or address
```
- Using `--force-with-lease` should probably all that's needed to get this to work
- stefanzweifel/git-auto-commit-action#2
=> Undo last attempt at fixing checkout

.github/auto-release-hotfix.yml, .github/auto-release.yml, .github/settings.yml
* Added  auto-release configs
* Added settings
=> Added org level config for workflows

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml
* Added CI GHA workflows
* First stage for migration all github actions to new org
=> Move CI workflows for GHA

.github/workflows/ci.yml
* Move GHA CI from shared workflows
=> Move GHA CI from shared workflows

.github/workflows/ci.yml
=> Move gha ci workflows 4

.github/workflows/ci.yml
=> Move gha ci workflows 5

.github/workflows/ci.yml
=> Fix CI releaser

.github/workflows/ci.yml, .github/workflows/shared-auto-release.yml, .github/workflows/shared-readme.yml, .github/workflows/shared-release-branches.yml
=> Added shared branches

.github/workflows/release-branch.yml
=> Fix release branch

.github/workflows/release-branch.yml
=> Fix shared workflows

.github/workflows/shared-readme.yml
=> Update shared workflows

.github/auto-release-hotfix.yml, .github/auto-release.yml
=> Fix tags template

README.md.gotmpl
=> Readme template fix
